### PR TITLE
I23 nonlinear programming

### PR DESCRIPTION
**Pull request by neginlashkari**
1- Safety radius is defined for the car robot to prevent its edge
colliding obstacles.
2- More comments are provided to explain the procedure, states, and
indexes.
3- Bezier generator is made to a function and saved in utilities folder.
4- Animation .gif file creator is made to a function and saved in
01-example folder. A simple example is also provided.
5- Optimization matlab function is saved to planning folder.

### CODE REVIEW

**Comment by chutsu** [comment]
Is this Pull Request not the same as #55  ?

**Comment by stevenwaslander** [comment]
I believe so, I should be able to resolve them both.

**Comment by stevenwaslander** [comment]
Other pull request merged directly into master. Works, no conflicts, better code and explanations.

**Comment by stevenwaslander** [comment]
Actually need some of these changes after all. What a challenge!

**Pull request merged**
