### PR TITLE
Issue 9 particle filter

### PR DESCRIPTION
**Pull request by chutsu**

### CODE REVIEW

**Comment by cbchau** [comment]
'Pause' at the end of 'expectation.m' causing program to run without stopping.

**Comment by cbchau** [comment]
I know the flyover plot of true state verses EKF/UKF/PF was originally that small, but is there a way to make it bigger to see as an improvement? 
Other than that, great coding and referencing in all the scripts and functions.

**Comment by rickeywang** [comment]
Much cleaner code, has helped me understand particle filters better!

Your code makes use of its own pre-packaged ekf and kf function, instead of the functions used in #7 and kf in #8. 

I'm not sure what everyone think of this... It make no difference from an operational standpoint, but I personally would prefer that there be one EKF/KF function in the entire repo.

**Comment by chutsu** [comment]
@rickeywang, Very much agree with unifying EKF/KF functions for the whole repo, it was just that for this assignment it wasn't going to be easy until we see how everyone is using the functions. I have however some ideas.

**Comment by chutsu** [comment]
e.g. for the universal EKF I propose the following functions: 

```
function x = EKF(dt, mu, R, Q, S)
    x = struct(
        "dt", dt,

        "mu", mu,
        "S", S,
        "R", R,
        "Q", Q,

        "mu_p", 0.0,
        "S_p", 0.0,
        "K", 0.0
    );
end

function [ekf] = ekf_prediction_update(ekf, g_func, G_func, u)
    g = feval(g_func, u, ekf.mu, ekf.dt);
    G = feval(G_func, u, ekf.mu, ekf.dt);

    ekf.mu_p = g;
    ekf.S_p = G * ekf.S * G' + ekf.R;
end

function [ekf] = ekf_measurement_update(ekf, h_func, H_func, y)
    h = feval(h_func, ekf.mu_p);
    H = feval(H_func, ekf.mu_p);

    K = ekf.S_p * transpose(H) * inv(H * ekf.S_p * transpose(H) + ekf.Q);
    ekf.mu = ekf.mu_p + K * (y - h);
    ekf.S = (eye(length(ekf.mu)) - K * H) * ekf.S_p;
end
```

I use a struct to encapsulate all the details needed for the EKF.

The special thing about the way I'm doing it in the above code is I'm using function pointers, this allows the user to pass in their own custom `g_func` that represents the motion model  that takes in the current input `u` and previous belief `mu` and time step `dt`. The same goes with the linearization of the motion model `G_func` there are many different ways the user can do this, so why not just let the user pass in the function that works out `G`.

**Comment by chutsu** [comment]
Example using my version of a universal EKF, simulating the Onmi-Robot we did for assignment 1.

```
source('lib/util.m');  %  source allows multiple functions in 1 file, instead of 1 function per file
source('lib/estimator/ekf.m');

function G_t = G(u, mu, dt)
    % length from wheel to center of chassis
    l = 0.3;

    % radius of wheel
    r = 0.25;

    % wheel constraints
    J_1 = [
        0, 1, l;
        -cos(pi / 6), -sin(pi / 6), l;
        cos(pi / 6), -sin(pi / 6), l;
    ];

    % wheel radius
    J_2 = [
        r, 0.0, 0.0;
        0.0, r, 0.0;
        0.0, 0.0, r;
    ];

    % constant terms
    C = inv(J_1) * J_2 * u * dt;

    % rotation matrix
    drot = [
        -sin(mu(3)), cos(mu(3)), 0;
        -cos(mu(3)), -sin(mu(3)), 0;
        0, 0, 0;
    ];
    drot_C = drot * C;

    % fill in the jacobian matrix G
    G_t = eye(3);
    G_t(1:2, 3) = drot_C(1:2);
end

function g_t = g(u, mu, dt)
    % length from wheel to center of chassis
    l = 0.3;

    % radius of wheel
    r = 0.25;

    % wheel constraints
    J_1 = [
        0, 1, l;
        -cos(pi / 6), -sin(pi / 6), l;
        cos(pi / 6), -sin(pi / 6), l;
    ];

    % wheel radius
    J_2 = [
        r, 0.0, 0.0;
        0.0, r, 0.0;
        0.0, 0.0, r;
    ];

    % rotation matrix
    rot = [
        cos(mu(3)), -sin(mu(3)), 0;
        sin(mu(3)), cos(mu(3)), 0;
        0, 0, 1;
    ];

    gdot_t = inv(rot) * inv(J_1) * J_2 * u;
    g_t = mu + gdot_t * dt;
end

function h = h(mu_p)
    H = eye(3);
    h = H * mu_p;
end

function H = H(mu_p)
    H = eye(3);
end

function simulation_loop(dt, nb_states, ekf)
    % simulation parameters
    t_end = 10;
    T = 0:dt:t_end;
    x_0 = [0; 0; 0];
    x = zeros(nb_states, length(T));
    x(:, 1) = x_0;
    y = zeros(length(ekf.Q), length(T));
    u = [0.0; -10.0; 10.0];

    % store
    mu = zeros(length(x_0));
    noise = zeros(length(ekf.R), length(x_0));

    % simulation
    for t = 2:length(T)
        % update state
        e = gaussian_noise(ekf.R);
        x(:, t) =  g(u, x(:, t - 1), dt) + e;
        noise(:, t) = e;

        % take measurement
        d = gaussian_noise(ekf.Q);
        y(:, t) = x(:, t) + d;

    % EKF
    [ekf] = ekf_prediction_update(ekf, @g, @G, u);
    [ekf] = ekf_measurement_update(ekf, @h, @H, y(:, t));

    % store ekf results
    mu(:, t) = ekf.mu;
    end

    plot_trajectory_2d(T, x, y, mu);
end


% simulation parameters
dt = 0.1;
mu = [0; 0; 0];
R = [
    0.05^2, 0, 0;
    0, 0.05^2, 0;
    0, 0, deg2rad(0.5)^2;
];
Q = [
    0.5^2, 0, 0;
    0, 0.5^2, 0;
    0, 0, deg2rad(10)^2;
];
S = eye(3);


% ekf
ekf = EKF(dt, mu, R, Q, S);
simulation_loop(dt, 3, ekf);
```

**Comment by LordBismaya** [comment]
I feel using struct is a good idea as it helps in more compact code using fewer variables. It is a good idea to unify EKF/KF functions across the repo. Although, Motion and measurement functions in the same file help in more compact code, wont it be a good idea to have separate files for them so that one out of many motion models could be chosen( such as diff Drive, bicycle, Omni etc.) and similarly measurements(1.range.2.bearing 3.both) with the help of a FLAG/argument? 
With that thought in mind, I am planning to adopt your struct suggestion and incorporate the required changes in my fastSlam code as well so that we can unify the code across the repo.

**Comment by chutsu** [comment]
Separate files for different motion models make perfect sense, I merely listed them in the same file as an example. You probably won't be able to run the above code in Matlab in any case, since in Matlab I do not think it supports writing functions and calling it within the same file. It will however work in Octave (open-source alternative to Matlab: btw Octave FTW). 

Being able to change different models in the EKF is as simple as just feeding in a different function pointer where your motion model function (etc) is defined, so no need for a flag argument for measurement model (1.range.2.bearing 3.both), else you will be hard coding measurement models into the EKF and that loses flexibility.

**Comment by chutsu** [comment]
As for unifying EKF, again I feel we should just submit with what we have and then fully evaluate how best to unify them at a later time. There are many variations how we can do this, using structs vs classes... etc.

**Comment by LordBismaya** [comment]
Great. I had the exact same thoughts. Unifying can be done at a later time. Yes. passing a pointer instead of flag is a good idea. Also, subfunctions can be defined within functions. I have done that earlier. But I guess that commit would be too much in the past to dig up..May be we are not talking about the same thing,but do have a look at the following link.
[http://www.mathworks.com/help/matlab/matlab_prog/local-functions.html](url)

**Pull request merged**
